title: "DataTalks.Club Free Courses"
description: "Master machine learning engineering, data engineering, MLOps, LLMs, and more with DataTalks.Club free courses (Zoomcamps)."
baseurl: "/courses"
url: "https://datatalks.club"

# Build settings
markdown: kramdown
highlighter: rouge

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed
  sourcemap: :always

plugins:
  - jekyll-feed
  - jekyll-sitemap

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .sass-cache/
  - .jekyll-cache/
  - .jekyll-metadata
